/*
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.singletonsd.kinesis.api.serial.api;

import au.com.singletonsd.kinesis.api.serial.api.ApiCallback;
import au.com.singletonsd.kinesis.api.serial.api.ApiClient;
import au.com.singletonsd.kinesis.api.serial.api.ApiException;
import au.com.singletonsd.kinesis.api.serial.api.ApiResponse;
import au.com.singletonsd.kinesis.api.serial.api.Configuration;
import au.com.singletonsd.kinesis.api.serial.api.Pair;
import au.com.singletonsd.kinesis.api.serial.api.ProgressRequestBody;
import au.com.singletonsd.kinesis.api.serial.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import au.com.singletonsd.kinesis.api.serial.model.CustomError;
import au.com.singletonsd.kinesis.api.serial.model.Deleted;
import au.com.singletonsd.kinesis.api.serial.model.Discounts;
import au.com.singletonsd.kinesis.api.serial.model.ResponseGetDiscount;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DiscountsApi {
    private ApiClient localVarApiClient;

    public DiscountsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DiscountsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for addDiscount
     * @param discounts  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addDiscountCall(Discounts discounts, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = discounts;

        // create path and map variables
        String localVarPath = "/discounts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addDiscountValidateBeforeCall(Discounts discounts, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'discounts' is set
        if (discounts == null) {
            throw new ApiException("Missing the required parameter 'discounts' when calling addDiscount(Async)");
        }
        

        okhttp3.Call localVarCall = addDiscountCall(discounts, _callback);
        return localVarCall;

    }

    /**
     * Add one discount.
     * Add one discount.
     * @param discounts  (required)
     * @return Discounts
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Discounts addDiscount(Discounts discounts) throws ApiException {
        ApiResponse<Discounts> localVarResp = addDiscountWithHttpInfo(discounts);
        return localVarResp.getData();
    }

    /**
     * Add one discount.
     * Add one discount.
     * @param discounts  (required)
     * @return ApiResponse&lt;Discounts&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Discounts> addDiscountWithHttpInfo(Discounts discounts) throws ApiException {
        okhttp3.Call localVarCall = addDiscountValidateBeforeCall(discounts, null);
        Type localVarReturnType = new TypeToken<Discounts>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add one discount. (asynchronously)
     * Add one discount.
     * @param discounts  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addDiscountAsync(Discounts discounts, final ApiCallback<Discounts> _callback) throws ApiException {

        okhttp3.Call localVarCall = addDiscountValidateBeforeCall(discounts, _callback);
        Type localVarReturnType = new TypeToken<Discounts>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteDiscount
     * @param id id to delete or search (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteDiscountCall(Long id, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/discounts/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteDiscountValidateBeforeCall(Long id, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteDiscount(Async)");
        }
        

        okhttp3.Call localVarCall = deleteDiscountCall(id, _callback);
        return localVarCall;

    }

    /**
     * Delete one discount.
     * Delete one discount.
     * @param id id to delete or search (required)
     * @return Long
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Long deleteDiscount(Long id) throws ApiException {
        ApiResponse<Long> localVarResp = deleteDiscountWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Delete one discount.
     * Delete one discount.
     * @param id id to delete or search (required)
     * @return ApiResponse&lt;Long&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Long> deleteDiscountWithHttpInfo(Long id) throws ApiException {
        okhttp3.Call localVarCall = deleteDiscountValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Long>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete one discount. (asynchronously)
     * Delete one discount.
     * @param id id to delete or search (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteDiscountAsync(Long id, final ApiCallback<Long> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteDiscountValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Long>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for editDiscount
     * @param id id to delete or search (required)
     * @param discounts  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call editDiscountCall(Long id, Discounts discounts, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = discounts;

        // create path and map variables
        String localVarPath = "/discounts/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call editDiscountValidateBeforeCall(Long id, Discounts discounts, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling editDiscount(Async)");
        }
        
        // verify the required parameter 'discounts' is set
        if (discounts == null) {
            throw new ApiException("Missing the required parameter 'discounts' when calling editDiscount(Async)");
        }
        

        okhttp3.Call localVarCall = editDiscountCall(id, discounts, _callback);
        return localVarCall;

    }

    /**
     * Edit one discount.
     * Edit one discount.
     * @param id id to delete or search (required)
     * @param discounts  (required)
     * @return Discounts
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Discounts editDiscount(Long id, Discounts discounts) throws ApiException {
        ApiResponse<Discounts> localVarResp = editDiscountWithHttpInfo(id, discounts);
        return localVarResp.getData();
    }

    /**
     * Edit one discount.
     * Edit one discount.
     * @param id id to delete or search (required)
     * @param discounts  (required)
     * @return ApiResponse&lt;Discounts&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Discounts> editDiscountWithHttpInfo(Long id, Discounts discounts) throws ApiException {
        okhttp3.Call localVarCall = editDiscountValidateBeforeCall(id, discounts, null);
        Type localVarReturnType = new TypeToken<Discounts>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Edit one discount. (asynchronously)
     * Edit one discount.
     * @param id id to delete or search (required)
     * @param discounts  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call editDiscountAsync(Long id, Discounts discounts, final ApiCallback<Discounts> _callback) throws ApiException {

        okhttp3.Call localVarCall = editDiscountValidateBeforeCall(id, discounts, _callback);
        Type localVarReturnType = new TypeToken<Discounts>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDiscountById
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDiscountByIdCall(Long id, Deleted deleted, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/discounts/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (deleted != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("deleted", deleted));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDiscountByIdValidateBeforeCall(Long id, Deleted deleted, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getDiscountById(Async)");
        }
        

        okhttp3.Call localVarCall = getDiscountByIdCall(id, deleted, _callback);
        return localVarCall;

    }

    /**
     * Get one discount.
     * Get one discount.
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @return Discounts
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Discounts getDiscountById(Long id, Deleted deleted) throws ApiException {
        ApiResponse<Discounts> localVarResp = getDiscountByIdWithHttpInfo(id, deleted);
        return localVarResp.getData();
    }

    /**
     * Get one discount.
     * Get one discount.
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @return ApiResponse&lt;Discounts&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Discounts> getDiscountByIdWithHttpInfo(Long id, Deleted deleted) throws ApiException {
        okhttp3.Call localVarCall = getDiscountByIdValidateBeforeCall(id, deleted, null);
        Type localVarReturnType = new TypeToken<Discounts>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get one discount. (asynchronously)
     * Get one discount.
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDiscountByIdAsync(Long id, Deleted deleted, final ApiCallback<Discounts> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDiscountByIdValidateBeforeCall(id, deleted, _callback);
        Type localVarReturnType = new TypeToken<Discounts>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDiscounts
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDiscountsCall(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/discounts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (skip != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("skip", skip));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (deleted != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("deleted", deleted));
        }

        if (metadata != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("metadata", metadata));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDiscountsValidateBeforeCall(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = getDiscountsCall(skip, limit, sort, deleted, metadata, _callback);
        return localVarCall;

    }

    /**
     * Get all discounts.
     * Get all discounts.
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @return ResponseGetDiscount
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ResponseGetDiscount getDiscounts(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata) throws ApiException {
        ApiResponse<ResponseGetDiscount> localVarResp = getDiscountsWithHttpInfo(skip, limit, sort, deleted, metadata);
        return localVarResp.getData();
    }

    /**
     * Get all discounts.
     * Get all discounts.
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @return ApiResponse&lt;ResponseGetDiscount&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResponseGetDiscount> getDiscountsWithHttpInfo(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata) throws ApiException {
        okhttp3.Call localVarCall = getDiscountsValidateBeforeCall(skip, limit, sort, deleted, metadata, null);
        Type localVarReturnType = new TypeToken<ResponseGetDiscount>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all discounts. (asynchronously)
     * Get all discounts.
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDiscountsAsync(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata, final ApiCallback<ResponseGetDiscount> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDiscountsValidateBeforeCall(skip, limit, sort, deleted, metadata, _callback);
        Type localVarReturnType = new TypeToken<ResponseGetDiscount>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
