/*
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.singletonsd.kinesis.api.serial.api;

import au.com.singletonsd.kinesis.api.serial.api.ApiCallback;
import au.com.singletonsd.kinesis.api.serial.api.ApiClient;
import au.com.singletonsd.kinesis.api.serial.api.ApiException;
import au.com.singletonsd.kinesis.api.serial.api.ApiResponse;
import au.com.singletonsd.kinesis.api.serial.api.Configuration;
import au.com.singletonsd.kinesis.api.serial.api.Pair;
import au.com.singletonsd.kinesis.api.serial.api.ProgressRequestBody;
import au.com.singletonsd.kinesis.api.serial.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import au.com.singletonsd.kinesis.api.serial.model.CustomError;
import au.com.singletonsd.kinesis.api.serial.model.Deleted;
import au.com.singletonsd.kinesis.api.serial.model.Products;
import au.com.singletonsd.kinesis.api.serial.model.RequestBulkProduct;
import au.com.singletonsd.kinesis.api.serial.model.ResponseGetProduct;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductsApi {
    private ApiClient localVarApiClient;

    public ProductsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProductsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for addProduct
     * @param products  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addProductCall(Products products, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = products;

        // create path and map variables
        String localVarPath = "/products";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addProductValidateBeforeCall(Products products, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'products' is set
        if (products == null) {
            throw new ApiException("Missing the required parameter 'products' when calling addProduct(Async)");
        }
        

        okhttp3.Call localVarCall = addProductCall(products, _callback);
        return localVarCall;

    }

    /**
     * Add one product.
     * Add one product.
     * @param products  (required)
     * @return Products
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Products addProduct(Products products) throws ApiException {
        ApiResponse<Products> localVarResp = addProductWithHttpInfo(products);
        return localVarResp.getData();
    }

    /**
     * Add one product.
     * Add one product.
     * @param products  (required)
     * @return ApiResponse&lt;Products&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Products> addProductWithHttpInfo(Products products) throws ApiException {
        okhttp3.Call localVarCall = addProductValidateBeforeCall(products, null);
        Type localVarReturnType = new TypeToken<Products>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add one product. (asynchronously)
     * Add one product.
     * @param products  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addProductAsync(Products products, final ApiCallback<Products> _callback) throws ApiException {

        okhttp3.Call localVarCall = addProductValidateBeforeCall(products, _callback);
        Type localVarReturnType = new TypeToken<Products>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for addProducts
     * @param requestBulkProduct  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addProductsCall(RequestBulkProduct requestBulkProduct, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = requestBulkProduct;

        // create path and map variables
        String localVarPath = "/products/bulk";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addProductsValidateBeforeCall(RequestBulkProduct requestBulkProduct, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'requestBulkProduct' is set
        if (requestBulkProduct == null) {
            throw new ApiException("Missing the required parameter 'requestBulkProduct' when calling addProducts(Async)");
        }
        

        okhttp3.Call localVarCall = addProductsCall(requestBulkProduct, _callback);
        return localVarCall;

    }

    /**
     * Add a list of products.
     * Add a list of products.
     * @param requestBulkProduct  (required)
     * @return List&lt;Products&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public List<Products> addProducts(RequestBulkProduct requestBulkProduct) throws ApiException {
        ApiResponse<List<Products>> localVarResp = addProductsWithHttpInfo(requestBulkProduct);
        return localVarResp.getData();
    }

    /**
     * Add a list of products.
     * Add a list of products.
     * @param requestBulkProduct  (required)
     * @return ApiResponse&lt;List&lt;Products&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Products>> addProductsWithHttpInfo(RequestBulkProduct requestBulkProduct) throws ApiException {
        okhttp3.Call localVarCall = addProductsValidateBeforeCall(requestBulkProduct, null);
        Type localVarReturnType = new TypeToken<List<Products>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add a list of products. (asynchronously)
     * Add a list of products.
     * @param requestBulkProduct  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addProductsAsync(RequestBulkProduct requestBulkProduct, final ApiCallback<List<Products>> _callback) throws ApiException {

        okhttp3.Call localVarCall = addProductsValidateBeforeCall(requestBulkProduct, _callback);
        Type localVarReturnType = new TypeToken<List<Products>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteProduct
     * @param id id to delete or search (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteProductCall(Long id, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteProductValidateBeforeCall(Long id, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteProduct(Async)");
        }
        

        okhttp3.Call localVarCall = deleteProductCall(id, _callback);
        return localVarCall;

    }

    /**
     * Delete one product.
     * Delete one product.
     * @param id id to delete or search (required)
     * @return Long
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Long deleteProduct(Long id) throws ApiException {
        ApiResponse<Long> localVarResp = deleteProductWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Delete one product.
     * Delete one product.
     * @param id id to delete or search (required)
     * @return ApiResponse&lt;Long&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Long> deleteProductWithHttpInfo(Long id) throws ApiException {
        okhttp3.Call localVarCall = deleteProductValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Long>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete one product. (asynchronously)
     * Delete one product.
     * @param id id to delete or search (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteProductAsync(Long id, final ApiCallback<Long> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteProductValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Long>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for editProduct
     * @param id id to delete or search (required)
     * @param products  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call editProductCall(Long id, Products products, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = products;

        // create path and map variables
        String localVarPath = "/products/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call editProductValidateBeforeCall(Long id, Products products, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling editProduct(Async)");
        }
        
        // verify the required parameter 'products' is set
        if (products == null) {
            throw new ApiException("Missing the required parameter 'products' when calling editProduct(Async)");
        }
        

        okhttp3.Call localVarCall = editProductCall(id, products, _callback);
        return localVarCall;

    }

    /**
     * Edit one product.
     * Edit one product.
     * @param id id to delete or search (required)
     * @param products  (required)
     * @return Products
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Products editProduct(Long id, Products products) throws ApiException {
        ApiResponse<Products> localVarResp = editProductWithHttpInfo(id, products);
        return localVarResp.getData();
    }

    /**
     * Edit one product.
     * Edit one product.
     * @param id id to delete or search (required)
     * @param products  (required)
     * @return ApiResponse&lt;Products&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Products> editProductWithHttpInfo(Long id, Products products) throws ApiException {
        okhttp3.Call localVarCall = editProductValidateBeforeCall(id, products, null);
        Type localVarReturnType = new TypeToken<Products>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Edit one product. (asynchronously)
     * Edit one product.
     * @param id id to delete or search (required)
     * @param products  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call editProductAsync(Long id, Products products, final ApiCallback<Products> _callback) throws ApiException {

        okhttp3.Call localVarCall = editProductValidateBeforeCall(id, products, _callback);
        Type localVarReturnType = new TypeToken<Products>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getProductById
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductByIdCall(Long id, Deleted deleted, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (deleted != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("deleted", deleted));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductByIdValidateBeforeCall(Long id, Deleted deleted, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getProductById(Async)");
        }
        

        okhttp3.Call localVarCall = getProductByIdCall(id, deleted, _callback);
        return localVarCall;

    }

    /**
     * Get one product.
     * Get one product.
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @return Products
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public Products getProductById(Long id, Deleted deleted) throws ApiException {
        ApiResponse<Products> localVarResp = getProductByIdWithHttpInfo(id, deleted);
        return localVarResp.getData();
    }

    /**
     * Get one product.
     * Get one product.
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @return ApiResponse&lt;Products&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Products> getProductByIdWithHttpInfo(Long id, Deleted deleted) throws ApiException {
        okhttp3.Call localVarCall = getProductByIdValidateBeforeCall(id, deleted, null);
        Type localVarReturnType = new TypeToken<Products>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get one product. (asynchronously)
     * Get one product.
     * @param id id to delete or search (required)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductByIdAsync(Long id, Deleted deleted, final ApiCallback<Products> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductByIdValidateBeforeCall(id, deleted, _callback);
        Type localVarReturnType = new TypeToken<Products>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getProducts
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsCall(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (skip != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("skip", skip));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (deleted != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("deleted", deleted));
        }

        if (metadata != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("metadata", metadata));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key", "bearer_auth", "main_auth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductsValidateBeforeCall(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = getProductsCall(skip, limit, sort, deleted, metadata, _callback);
        return localVarCall;

    }

    /**
     * Get all products.
     * Get all products.
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @return ResponseGetProduct
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ResponseGetProduct getProducts(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata) throws ApiException {
        ApiResponse<ResponseGetProduct> localVarResp = getProductsWithHttpInfo(skip, limit, sort, deleted, metadata);
        return localVarResp.getData();
    }

    /**
     * Get all products.
     * Get all products.
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @return ApiResponse&lt;ResponseGetProduct&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResponseGetProduct> getProductsWithHttpInfo(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata) throws ApiException {
        okhttp3.Call localVarCall = getProductsValidateBeforeCall(skip, limit, sort, deleted, metadata, null);
        Type localVarReturnType = new TypeToken<ResponseGetProduct>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all products. (asynchronously)
     * Get all products.
     * @param skip number of item to skip (optional, default to 0)
     * @param limit max records to return (optional, default to 10)
     * @param sort sort by property. (optional)
     * @param deleted Get all, deleted, not deleted data. Default not deleted. (optional, default to ACTIVE)
     * @param metadata If metadata is needed (for pagination controls) (optional, default to false)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Request OK. </td><td>  * Limit -  <br>  * Remaining -  <br>  * Reset -  <br>  </td></tr>
        <tr><td> 204 </td><td> Response is empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Some parameters are missing or badly entered. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Entity not found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Illegal input for operation. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsAsync(Integer skip, Integer limit, String sort, Deleted deleted, Boolean metadata, final ApiCallback<ResponseGetProduct> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductsValidateBeforeCall(skip, limit, sort, deleted, metadata, _callback);
        Type localVarReturnType = new TypeToken<ResponseGetProduct>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
