openapi: 3.0.0
info:
  version: 1.0.0
  title: Kinesis Code Exercise API
  termsOfService: 'https://kinesis.singletonsd.com.au/terms/'
  contact:
    email: patoperpetua@singletonsd.com.au
    url: 'http://kinesis.singletonsd.com.au/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: >
    This is an API to interact with Kineses Code Exercise API

    # Introduction

    This API allow to create, modify and delete products, discounts, and orders.

    # User Authentication

    This API does not contain any kind of user validation but It request to have
    a valid authentication user to interact with it.
    For more information about user Authentication, please refer to
    [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/).
externalDocs:
  description: Find out how to interact with Kinesis APIs.
  url: 'https://kinesis.singletonsd.com.au/'
tags:
  - name: Discounts
    description: Operations about discounts.
  - name: Products
    description: Operations about products.
  - name: Orders
    description: Operations about orders.
servers:
  - url: 'http://localhost:8000'
  - url: 'http://kinesis.singletonsd.com.au'
