/**
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../model/models';
import { Deleted } from '../model/models';
import { Discounts } from '../model/models';
import { ResponseGetDiscount } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DiscountsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Add one discount.
     * Add one discount.
     * @param discounts 
     */
    addDiscount(discounts: Discounts, extraHttpRequestParams?: any): Observable<Discounts>;

    /**
     * Delete one discount.
     * Delete one discount.
     * @param id id to delete or search
     */
    deleteDiscount(id: number, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Edit one discount.
     * Edit one discount.
     * @param id id to delete or search
     * @param discounts 
     */
    editDiscount(id: number, discounts: Discounts, extraHttpRequestParams?: any): Observable<Discounts>;

    /**
     * Get one discount.
     * Get one discount.
     * @param id id to delete or search
     * @param deleted Get all, deleted, not deleted data. Default not deleted.
     */
    getDiscountById(id: number, deleted?: Deleted, extraHttpRequestParams?: any): Observable<Discounts>;

    /**
     * Get all discounts.
     * Get all discounts.
     * @param skip number of item to skip
     * @param limit max records to return
     * @param sort sort by property.
     * @param deleted Get all, deleted, not deleted data. Default not deleted.
     * @param metadata If metadata is needed (for pagination controls)
     */
    getDiscounts(skip?: number, limit?: number, sort?: string, deleted?: Deleted, metadata?: boolean, extraHttpRequestParams?: any): Observable<ResponseGetDiscount>;

}
