/**
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../model/models';
import { Deleted } from '../model/models';
import { Products } from '../model/models';
import { RequestBulkProduct } from '../model/models';
import { ResponseGetProduct } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Add one product.
     * Add one product.
     * @param products 
     */
    addProduct(products: Products, extraHttpRequestParams?: any): Observable<Products>;

    /**
     * Add a list of products.
     * Add a list of products.
     * @param requestBulkProduct 
     */
    addProducts(requestBulkProduct: RequestBulkProduct, extraHttpRequestParams?: any): Observable<Array<Products>>;

    /**
     * Delete one product.
     * Delete one product.
     * @param id id to delete or search
     */
    deleteProduct(id: number, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Edit one product.
     * Edit one product.
     * @param id id to delete or search
     * @param products 
     */
    editProduct(id: number, products: Products, extraHttpRequestParams?: any): Observable<Products>;

    /**
     * Get one product.
     * Get one product.
     * @param id id to delete or search
     * @param deleted Get all, deleted, not deleted data. Default not deleted.
     */
    getProductById(id: number, deleted?: Deleted, extraHttpRequestParams?: any): Observable<Products>;

    /**
     * Get all products.
     * Get all products.
     * @param skip number of item to skip
     * @param limit max records to return
     * @param sort sort by property.
     * @param deleted Get all, deleted, not deleted data. Default not deleted.
     * @param metadata If metadata is needed (for pagination controls)
     */
    getProducts(skip?: number, limit?: number, sort?: string, deleted?: Deleted, metadata?: boolean, extraHttpRequestParams?: any): Observable<ResponseGetProduct>;

}
