/*
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.singletonsd.kinesis.api.serial.model;

import java.util.Objects;
import java.util.Arrays;
import au.com.singletonsd.kinesis.api.serial.model.DiscountType;
import au.com.singletonsd.kinesis.api.serial.model.Products;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import java.io.Serializable;

/**
 * Discount&#39;s information.
 */
@ApiModel(description = "Discount's information.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-19T22:57:20.866150+10:00[Australia/Brisbane]")
public class Discounts implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DISCOUNT_TYPE = "discountType";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_TYPE)
  private DiscountType discountType = DiscountType.CHEAPEST;

  public static final String SERIALIZED_NAME_ITEMS_X_QUANTITY = "itemsXQuantity";
  @SerializedName(SERIALIZED_NAME_ITEMS_X_QUANTITY)
  private Long itemsXQuantity;

  public static final String SERIALIZED_NAME_ITEMS_Y_QUANTITY = "itemsYQuantity";
  @SerializedName(SERIALIZED_NAME_ITEMS_Y_QUANTITY)
  private Long itemsYQuantity;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT)
  private Float discount;

  public static final String SERIALIZED_NAME_MAX_DISCOUNT_TO_APPLY = "maxDiscountToApply";
  @SerializedName(SERIALIZED_NAME_MAX_DISCOUNT_TO_APPLY)
  private Long maxDiscountToApply;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  private List<Products> products = null;

  public static final String SERIALIZED_NAME_ID_PRODUCTS = "idProducts";
  @SerializedName(SERIALIZED_NAME_ID_PRODUCTS)
  private List<Long> idProducts = null;

  public static final String SERIALIZED_NAME_DELETED = "deleted";
  @SerializedName(SERIALIZED_NAME_DELETED)
  private Boolean deleted = false;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private OffsetDateTime modifiedAt;


  public Discounts id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Discount&#39;s Id.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Discount's Id.")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Discounts name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Discounts discountType(DiscountType discountType) {
    
    this.discountType = discountType;
    return this;
  }

   /**
   * Get discountType
   * @return discountType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DiscountType getDiscountType() {
    return discountType;
  }


  public void setDiscountType(DiscountType discountType) {
    this.discountType = discountType;
  }


  public Discounts itemsXQuantity(Long itemsXQuantity) {
    
    this.itemsXQuantity = itemsXQuantity;
    return this;
  }

   /**
   * indicate the number of ‘X’ items that a customer will have to buy to get the discount.
   * @return itemsXQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "indicate the number of ‘X’ items that a customer will have to buy to get the discount.")

  public Long getItemsXQuantity() {
    return itemsXQuantity;
  }


  public void setItemsXQuantity(Long itemsXQuantity) {
    this.itemsXQuantity = itemsXQuantity;
  }


  public Discounts itemsYQuantity(Long itemsYQuantity) {
    
    this.itemsYQuantity = itemsYQuantity;
    return this;
  }

   /**
   * indicate the number of ‘Y’ items which will receive a discount.
   * @return itemsYQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "indicate the number of ‘Y’ items which will receive a discount.")

  public Long getItemsYQuantity() {
    return itemsYQuantity;
  }


  public void setItemsYQuantity(Long itemsYQuantity) {
    this.itemsYQuantity = itemsYQuantity;
  }


  public Discounts discount(Float discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * indicate the % of discount of &#39;Y&#39; items. this number goes from 0 to 100.
   * minimum: 0
   * maximum: 100
   * @return discount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "indicate the % of discount of 'Y' items. this number goes from 0 to 100.")

  public Float getDiscount() {
    return discount;
  }


  public void setDiscount(Float discount) {
    this.discount = discount;
  }


  public Discounts maxDiscountToApply(Long maxDiscountToApply) {
    
    this.maxDiscountToApply = maxDiscountToApply;
    return this;
  }

   /**
   * indicate the amount of discounts that can be applied in a single order.
   * @return maxDiscountToApply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "indicate the amount of discounts that can be applied in a single order.")

  public Long getMaxDiscountToApply() {
    return maxDiscountToApply;
  }


  public void setMaxDiscountToApply(Long maxDiscountToApply) {
    this.maxDiscountToApply = maxDiscountToApply;
  }


  public Discounts products(List<Products> products) {
    
    this.products = products;
    return this;
  }

  public Discounts addProductsItem(Products productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<Products>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Products> getProducts() {
    return products;
  }


  public void setProducts(List<Products> products) {
    this.products = products;
  }


  public Discounts idProducts(List<Long> idProducts) {
    
    this.idProducts = idProducts;
    return this;
  }

  public Discounts addIdProductsItem(Long idProductsItem) {
    if (this.idProducts == null) {
      this.idProducts = new ArrayList<Long>();
    }
    this.idProducts.add(idProductsItem);
    return this;
  }

   /**
   * Get idProducts
   * @return idProducts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Long> getIdProducts() {
    return idProducts;
  }


  public void setIdProducts(List<Long> idProducts) {
    this.idProducts = idProducts;
  }


  public Discounts deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


   /**
   * Object&#39;s created time.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Object's created time.")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Object&#39;s modified time.
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Object's modified time.")

  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Discounts discounts = (Discounts) o;
    return Objects.equals(this.id, discounts.id) &&
        Objects.equals(this.name, discounts.name) &&
        Objects.equals(this.discountType, discounts.discountType) &&
        Objects.equals(this.itemsXQuantity, discounts.itemsXQuantity) &&
        Objects.equals(this.itemsYQuantity, discounts.itemsYQuantity) &&
        Objects.equals(this.discount, discounts.discount) &&
        Objects.equals(this.maxDiscountToApply, discounts.maxDiscountToApply) &&
        Objects.equals(this.products, discounts.products) &&
        Objects.equals(this.idProducts, discounts.idProducts) &&
        Objects.equals(this.deleted, discounts.deleted) &&
        Objects.equals(this.createdAt, discounts.createdAt) &&
        Objects.equals(this.modifiedAt, discounts.modifiedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, discountType, itemsXQuantity, itemsYQuantity, discount, maxDiscountToApply, products, idProducts, deleted, createdAt, modifiedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Discounts {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    discountType: ").append(toIndentedString(discountType)).append("\n");
    sb.append("    itemsXQuantity: ").append(toIndentedString(itemsXQuantity)).append("\n");
    sb.append("    itemsYQuantity: ").append(toIndentedString(itemsYQuantity)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    maxDiscountToApply: ").append(toIndentedString(maxDiscountToApply)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    idProducts: ").append(toIndentedString(idProducts)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

