/*
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.singletonsd.kinesis.api.serial.model;

import java.util.Objects;
import java.util.Arrays;
import au.com.singletonsd.kinesis.api.serial.model.Discounts;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import java.io.Serializable;

/**
 * Product&#39;s information.
 */
@ApiModel(description = "Product's information.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-19T22:57:20.866150+10:00[Australia/Brisbane]")
public class Products implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Float price;

  public static final String SERIALIZED_NAME_ID_DISCOUNTS = "idDiscounts";
  @SerializedName(SERIALIZED_NAME_ID_DISCOUNTS)
  private List<Long> idDiscounts = null;

  public static final String SERIALIZED_NAME_DISCOUNTS = "discounts";
  @SerializedName(SERIALIZED_NAME_DISCOUNTS)
  private List<Discounts> discounts = null;

  public static final String SERIALIZED_NAME_DELETED = "deleted";
  @SerializedName(SERIALIZED_NAME_DELETED)
  private Boolean deleted = false;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private OffsetDateTime modifiedAt;


  public Products id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Product&#39;s Id.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Product's Id.")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Products name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Products price(Float price) {
    
    this.price = price;
    return this;
  }

   /**
   * Object&#39;s price.
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Object's price.")

  public Float getPrice() {
    return price;
  }


  public void setPrice(Float price) {
    this.price = price;
  }


  public Products idDiscounts(List<Long> idDiscounts) {
    
    this.idDiscounts = idDiscounts;
    return this;
  }

  public Products addIdDiscountsItem(Long idDiscountsItem) {
    if (this.idDiscounts == null) {
      this.idDiscounts = new ArrayList<Long>();
    }
    this.idDiscounts.add(idDiscountsItem);
    return this;
  }

   /**
   * Get idDiscounts
   * @return idDiscounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Long> getIdDiscounts() {
    return idDiscounts;
  }


  public void setIdDiscounts(List<Long> idDiscounts) {
    this.idDiscounts = idDiscounts;
  }


  public Products discounts(List<Discounts> discounts) {
    
    this.discounts = discounts;
    return this;
  }

  public Products addDiscountsItem(Discounts discountsItem) {
    if (this.discounts == null) {
      this.discounts = new ArrayList<Discounts>();
    }
    this.discounts.add(discountsItem);
    return this;
  }

   /**
   * Get discounts
   * @return discounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Discounts> getDiscounts() {
    return discounts;
  }


  public void setDiscounts(List<Discounts> discounts) {
    this.discounts = discounts;
  }


  public Products deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


   /**
   * Object&#39;s created time.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Object's created time.")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Object&#39;s modified time.
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Object's modified time.")

  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Products products = (Products) o;
    return Objects.equals(this.id, products.id) &&
        Objects.equals(this.name, products.name) &&
        Objects.equals(this.price, products.price) &&
        Objects.equals(this.idDiscounts, products.idDiscounts) &&
        Objects.equals(this.discounts, products.discounts) &&
        Objects.equals(this.deleted, products.deleted) &&
        Objects.equals(this.createdAt, products.createdAt) &&
        Objects.equals(this.modifiedAt, products.modifiedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, price, idDiscounts, discounts, deleted, createdAt, modifiedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Products {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    idDiscounts: ").append(toIndentedString(idDiscounts)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

