/**
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Products } from './products';
import { DiscountType } from './discountType';


/**
 * Discount\'s information.
 */
export interface Discounts { 
    /**
     * Discount\'s Id.
     */
    id: number;
    name?: string;
    discountType?: DiscountType;
    /**
     * indicate the number of ‘X’ items that a customer will have to buy to get the discount.
     */
    itemsXQuantity?: number;
    /**
     * indicate the number of ‘Y’ items which will receive a discount.
     */
    itemsYQuantity?: number;
    /**
     * indicate the % of discount of \'Y\' items. this number goes from 0 to 100.
     */
    discount?: number;
    /**
     * indicate the amount of discounts that can be applied in a single order.
     */
    maxDiscountToApply?: number;
    products?: Array<Products>;
    idProducts?: Array<number>;
    deleted?: boolean;
    /**
     * Object\'s created time.
     */
    readonly createdAt?: string;
    /**
     * Object\'s modified time.
     */
    readonly modifiedAt?: string;
}

