/**
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Discounts } from './discounts';


/**
 * Product\'s information.
 */
export interface Products { 
    /**
     * Product\'s Id.
     */
    id: number;
    name?: string;
    /**
     * Object\'s price.
     */
    price?: number;
    idDiscounts?: Array<number>;
    discounts?: Array<Discounts>;
    deleted?: boolean;
    /**
     * Object\'s created time.
     */
    readonly createdAt?: string;
    /**
     * Object\'s modified time.
     */
    readonly modifiedAt?: string;
}

