get:
  tags:
    - Products
  summary: Get all products.
  description: Get all products.
  operationId: getProducts
  parameters:
    - $ref: '#/components/parameters/Page'
    - $ref: '#/components/parameters/Size'
    - $ref: '#/components/parameters/Sort'
    - $ref: '#/components/parameters/Deleted'
    - $ref: '#/components/parameters/Metadata'
  responses:
    '200':
      description: Request OK.
      headers:
        Limit:
          $ref: "#/components/headers/Limit"
        Remaining:
          $ref: "#/components/headers/Remaining"
        Reset:
          $ref: "#/components/headers/Reset"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseGetProduct"
    '204':
      $ref: '#/components/responses/204'
    '400':
      $ref: '#/components/responses/400'
    '401':
      $ref: '#/components/responses/401'
    '404':
      $ref: '#/components/responses/404'
    '405':
      $ref: '#/components/responses/405'
  x-swagger-router-controller: Products
  security:
    - api_key: []
    - bearer_auth: []
    - main_auth:
      - 'read:product'
post:
  tags:
    - "Products"
  summary: "Add one product."
  description: "Add one product."
  operationId: "addProduct"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Products"
  responses:
    '200':
      description: "Request OK."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Products"
    '400':
      $ref: "#/components/responses/400"
    '401':
      $ref: "#/components/responses/401"
    '404':
      $ref: "#/components/responses/404"
    '405':
      $ref: "#/components/responses/405"
  x-swagger-router-controller: "Products"
  security:
    - api_key: []
    - bearer_auth: []
    - main_auth:
      - 'create:product'
