/*
 * Kinesis Code Exercise API
 * This is an API to interact with Kineses Code Exercise API # Introduction This API allow to create, modify and delete products, discounts, and orders. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Kinesis Authentication API](https://auth.kinesis.singleton.com.au/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: patoperpetua@singletonsd.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.singletonsd.kinesis.api.serial.api;

import au.com.singletonsd.kinesis.api.serial.api.ApiException;
import au.com.singletonsd.kinesis.api.serial.model.CustomError;
import au.com.singletonsd.kinesis.api.serial.model.Deleted;
import au.com.singletonsd.kinesis.api.serial.model.Orders;
import au.com.singletonsd.kinesis.api.serial.model.Products;
import au.com.singletonsd.kinesis.api.serial.model.ResponseGetOrder;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    
    /**
     * Add one order.
     *
     * Add one order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addOrderTest() throws ApiException {
        Orders orders = null;
        Orders response = api.addOrder(orders);

        // TODO: test validations
    }
    
    /**
     * Add one product to order.
     *
     * Add product to order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProductOrderTest() throws ApiException {
        Long id = null;
        Products products = null;
        Orders response = api.addProductOrder(id, products);

        // TODO: test validations
    }
    
    /**
     * Delete one order.
     *
     * Delete one order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOrderTest() throws ApiException {
        Long id = null;
        Long response = api.deleteOrder(id);

        // TODO: test validations
    }
    
    /**
     * Edit one order.
     *
     * Edit one order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editOrderTest() throws ApiException {
        Long id = null;
        Orders orders = null;
        Orders response = api.editOrder(id, orders);

        // TODO: test validations
    }
    
    /**
     * Get one order.
     *
     * Get one order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderByIdTest() throws ApiException {
        Long id = null;
        Deleted deleted = null;
        Orders response = api.getOrderById(id, deleted);

        // TODO: test validations
    }
    
    /**
     * Get all orders.
     *
     * Get all orders.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrdersTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        String sort = null;
        Deleted deleted = null;
        Boolean metadata = null;
        ResponseGetOrder response = api.getOrders(page, size, sort, deleted, metadata);

        // TODO: test validations
    }
    
}
